// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
	"time"
)

type Session struct {
	ID     int64  `json:"id"`
	TaskID int64  `json:"task_id"`
	Name   string `json:"name"`
	// This is a description of the session, what you will do
	Description sql.NullString `json:"description"`
	// Ones goals for the session
	Goal sql.NullString `json:"goal"`
	// This is where one want to carry out the session
	Location  sql.NullString `json:"location"`
	Attended  bool           `json:"attended"`
	StartTime time.Time      `json:"startTime"`
	// This is duration in minutes
	Duration  int32     `json:"duration"`
	CreatedAt time.Time `json:"createdAt"`
}

type Skill struct {
	ID        int64     `json:"id"`
	Learner   string    `json:"learner"`
	Name      string    `json:"name"`
	Score     int64     `json:"score"`
	CreatedAt time.Time `json:"createdAt"`
}

type Task struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	SkillID   int64     `json:"skill_id"`
	CreatedAt time.Time `json:"createdAt"`
}
