// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteSession(ctx context.Context, id int64) error
	DeleteSkillByID(ctx context.Context, id int64) error
	DeleteTask(ctx context.Context, id int64) error
	GetAllSessions(ctx context.Context, arg GetAllSessionsParams) ([]Session, error)
	GetAllSessionsBySkill(ctx context.Context, arg GetAllSessionsBySkillParams) ([]Session, error)
	GetAllSessionsByTask(ctx context.Context, arg GetAllSessionsByTaskParams) ([]Session, error)
	GetAllSkills(ctx context.Context, arg GetAllSkillsParams) ([]Skill, error)
	GetSessionByID(ctx context.Context, id int64) (Session, error)
	GetSkillByID(ctx context.Context, id int64) (Skill, error)
	GetSkillBySession(ctx context.Context, id int64) (Skill, error)
	GetSkillsByLearner(ctx context.Context, arg GetSkillsByLearnerParams) ([]Skill, error)
	GetTaskByID(ctx context.Context, id int64) (Task, error)
	GetTasksByLearnerName(ctx context.Context, arg GetTasksByLearnerNameParams) ([]Task, error)
	GetTasksBySkillID(ctx context.Context, arg GetTasksBySkillIDParams) ([]Task, error)
	GetUpcomingSessions(ctx context.Context, arg GetUpcomingSessionsParams) ([]Session, error)
	GetUpcomingSessionsBySkill(ctx context.Context, arg GetUpcomingSessionsBySkillParams) ([]Session, error)
	GetUpcomingSessionsByTask(ctx context.Context, arg GetUpcomingSessionsByTaskParams) ([]Session, error)
	IncreaseSkillScore(ctx context.Context, arg IncreaseSkillScoreParams) (Skill, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
